$base    = "c:\Users\boomb\Documents\_319H\MSPM0_ValvanoWare\ECE319K_Lab9H\images"
$tetris  = "$base\tetris"
$pentris = "$base\pentris\pentris"
$out = [System.Text.StringBuilder]::new()

function ConvertBMP($srcPath, $varName) {
    $bytes  = [System.IO.File]::ReadAllBytes($srcPath)
    $bmpW   = [System.BitConverter]::ToInt32($bytes, 18)
    $bmpH   = [System.BitConverter]::ToInt32($bytes, 22)
    $offset = [System.BitConverter]::ToInt32($bytes, 10)
    $stride = [int][Math]::Ceiling($bmpW * 3 / 4.0) * 4

    [void]$out.AppendLine("// $([System.IO.Path]::GetFileName($srcPath))  ${bmpW}w x ${bmpH}h")
    [void]$out.AppendLine("const uint16_t ${varName}[] = {")

    # BMP stores rows bottom-to-top. ST7735_DrawBitmap starts at i=w*(h-1)
    # (last row first) and works backwards, so array[0] = visual BOTTOM row.
    # Read BMP in natural file order (row 0 = visual bottom) — NO flip.
    for ($row = 0; $row -lt $bmpH; $row++) {
        $rowStart = $offset + $row * $stride
        $line = " "
        for ($col = 0; $col -lt $bmpW; $col++) {
            $i  = $rowStart + $col * 3
            $B  = $bytes[$i]; $G = $bytes[$i+1]; $R = $bytes[$i+2]
            $c  = (($R -band 0xF8) -shl 8) -bor (($G -band 0xFC) -shl 3) -bor ($B -shr 3)
            $line += "0x{0:X4}," -f $c
        }
        [void]$out.AppendLine($line)
    }
    [void]$out.AppendLine("};")
    [void]$out.AppendLine("")
}

[void]$out.AppendLine("// tetris_images.h -- auto-generated by gen_tetris.ps1")
[void]$out.AppendLine("// ST7735_DrawBitmap expects array[0]=bottom row (native BMP order).")
[void]$out.AppendLine("// Call: ST7735_DrawBitmap(x, top+h-1, arr, w, h)")
[void]$out.AppendLine("#ifndef __tetris_images_h")
[void]$out.AppendLine("#define __tetris_images_h")
[void]$out.AppendLine("#include <stdint.h>")
[void]$out.AppendLine("")

# Tetris piece sprites (4-cell)
ConvertBMP "$tetris\L-purple.bmp"    "TetrisL"   # 16x24  L piece (purple)
ConvertBMP "$tetris\line-brown.bmp"  "TetrisI"   # 8x24   I piece (brown)
ConvertBMP "$tetris\square-blue.bmp" "TetrisO"   # 16x16  O piece (blue)
ConvertBMP "$tetris\T-4.bmp"         "TetrisT"   # 24x16  T piece (gray)
ConvertBMP "$tetris\z-green.bmp"     "TetrisZ"   # 24x16  Z piece (green)
ConvertBMP "$tetris\8 bit example.bmp" "TetrisBG" # 128x160 full-screen background

# Pentris piece sprites (5-cell)
ConvertBMP "$pentris\T5-red.bmp"        "PentrisT"  # 24x24  T5 piece (red)
ConvertBMP "$pentris\L5- purple.bmp"    "PentrisL"  # 16x32  L5 piece (purple)
ConvertBMP "$pentris\square5-blue.bmp"  "PentrisO"  # 16x24  square5 piece (blue)
ConvertBMP "$pentris\l5-brown.bmp"      "PentrisI"  # 8x40   line5 piece (brown)
ConvertBMP "$pentris\z5- green.bmp"     "PentrisZ"  # 32x16  Z5 piece (green)

[void]$out.AppendLine("#endif /* __tetris_images_h */")

$out.ToString() | Out-File -FilePath "$base\tetris_images.h" -Encoding ascii
$lines = ($out.ToString() -split "`n").Count
Write-Host "Done. Lines: $lines"
Write-Host "Size: $([System.IO.FileInfo]::new("$base\tetris_images.h").Length) bytes"
